- hosts: ansible_host
  gather_facts: no

  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: ddung1203
        password: "{{ lookup('env', 'PASS') }}"
        reauthorize: yes

    - name: Build and Push Image
      docker_image:
        build:
          path: /home/ubuntu/nodejs/
        name: ddung1203/node-js
        tag: "{{ lookup('env', 'BUILD_NUMBER') }}"
        push: yes
        source: build
